version: "3.1"

services:
  nodejs-reps-service:
    container_name: repos-service
    build: .
    image: repos-service:v1
    ports:
      - "8000:8000"
    restart: always
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
